name: Deploy Flask App to VPS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH agent
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy to VPS
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no rishabhvyas@178.16.137.226 << 'EOF'
          cd /home/rishabhvyas/DataDashboard
          git reset --hard HEAD
          git clean -fd
          # Ensure secrets files are not overwritten
          git pull origin main  # Pull the latest changes
          git stash pop  # Restore any stashed files

          # Activate virtual environment and install dependencies
          source /home/rishabhvyas/DataDashboard/venv/bin/activate
          pip install -r requirements.txt

          # Restart the Flask application service
          sudo systemctl restart datadashboard.service
        EOF
